/**
 * @roxi/routify 2.7.3
 * File generated Tue Mar 08 2022 17:44:01 GMT+0000 (Greenwich Mean Time)
 */

export const __version = '2.7.3';
export const __timestamp = '2022-03-08T17:44:01.046Z';

//buildRoutes
import { buildClientTree } from '@roxi/routify/runtime/buildRoutes';

//imports

//options
export const options = {};

//tree
export const _tree = {
  name: '_layout',
  filepath: '/_layout.svelte',
  root: true,
  ownMeta: {},
  absolutePath: '/home/jaskaran/repos/enki-website/src/pages/_layout.svelte',
  children: [
    {
      isFile: true,
      isDir: false,
      file: '_fallback.svelte',
      filepath: '/_fallback.svelte',
      name: '_fallback',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/_fallback.svelte',
      importPath: '../src/pages/_fallback.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: true,
      isPage: false,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/_fallback',
      id: '__fallback',
      component: () =>
        import('../src/pages/_fallback.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/about/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/about/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: 'index.svelte',
          filepath: '/about/index.svelte',
          name: 'index',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/about/index.svelte',
          importPath: '../src/pages/about/index.svelte',
          isLayout: false,
          isReset: false,
          isIndex: true,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/about/index',
          id: '_about_index',
          component: () =>
            import('../src/pages/about/index.svelte').then((m) => m.default),
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/about/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/about',
      id: '_about__layout',
      component: () =>
        import('../src/pages/about/_layout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/classes/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/classes/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: 'beginners.svelte',
          filepath: '/classes/beginners.svelte',
          name: 'beginners',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/classes/beginners.svelte',
          importPath: '../src/pages/classes/beginners.svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/classes/beginners',
          id: '_classes_beginners',
          component: () =>
            import('../src/pages/classes/beginners.svelte').then(
              (m) => m.default
            ),
        },
        {
          isFile: true,
          isDir: false,
          file: 'index.svelte',
          filepath: '/classes/index.svelte',
          name: 'index',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/classes/index.svelte',
          importPath: '../src/pages/classes/index.svelte',
          isLayout: false,
          isReset: false,
          isIndex: true,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/classes/index',
          id: '_classes_index',
          component: () =>
            import('../src/pages/classes/index.svelte').then((m) => m.default),
        },
        {
          isFile: true,
          isDir: false,
          file: 'wedding-rings.svelte',
          filepath: '/classes/wedding-rings.svelte',
          name: 'wedding-rings',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/classes/wedding-rings.svelte',
          importPath: '../src/pages/classes/wedding-rings.svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/classes/wedding-rings',
          id: '_classes_weddingRings',
          component: () =>
            import('../src/pages/classes/wedding-rings.svelte').then(
              (m) => m.default
            ),
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/classes/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/classes',
      id: '_classes__layout',
      component: () =>
        import('../src/pages/classes/_layout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/contact/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/contact/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: 'index.svelte',
          filepath: '/contact/index.svelte',
          name: 'index',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/contact/index.svelte',
          importPath: '../src/pages/contact/index.svelte',
          isLayout: false,
          isReset: false,
          isIndex: true,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/contact/index',
          id: '_contact_index',
          component: () =>
            import('../src/pages/contact/index.svelte').then((m) => m.default),
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/contact/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/contact',
      id: '_contact__layout',
      component: () =>
        import('../src/pages/contact/_layout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'index.svelte',
      filepath: '/index.svelte',
      name: 'index',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/repos/enki-website/src/pages/index.svelte',
      importPath: '../src/pages/index.svelte',
      isLayout: false,
      isReset: false,
      isIndex: true,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/index',
      id: '_index',
      component: () =>
        import('../src/pages/index.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/payment/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/payment/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: 'success.svelte',
          filepath: '/payment/success.svelte',
          name: 'success',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/payment/success.svelte',
          importPath: '../src/pages/payment/success.svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/payment/success',
          id: '_payment_success',
          component: () =>
            import('../src/pages/payment/success.svelte').then(
              (m) => m.default
            ),
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/payment/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/payment',
      id: '_payment__layout',
      component: () =>
        import('../src/pages/payment/_layout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/repairs/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/repairs/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: 'index.svelte',
          filepath: '/repairs/index.svelte',
          name: 'index',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/repairs/index.svelte',
          importPath: '../src/pages/repairs/index.svelte',
          isLayout: false,
          isReset: false,
          isIndex: true,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/repairs/index',
          id: '_repairs_index',
          component: () =>
            import('../src/pages/repairs/index.svelte').then((m) => m.default),
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/repairs/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/repairs',
      id: '_repairs__layout',
      component: () =>
        import('../src/pages/repairs/_layout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: true,
      file: '_layout.svelte',
      filepath: '/shop/_layout.svelte',
      name: '_layout',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/repos/enki-website/src/pages/shop/_layout.svelte',
      children: [
        {
          isFile: true,
          isDir: false,
          file: '[category].svelte',
          filepath: '/shop/[category].svelte',
          name: '[category]',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/shop/[category].svelte',
          importPath: '../src/pages/shop/[category].svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/:category',
          id: '_shop__category',
          component: () =>
            import('../src/pages/shop/[category].svelte').then(
              (m) => m.default
            ),
        },
        {
          isFile: false,
          isDir: true,
          file: 'basket',
          filepath: '/shop/basket',
          name: 'basket',
          ext: '',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/shop/basket',
          children: [
            {
              isFile: true,
              isDir: false,
              file: 'index.svelte',
              filepath: '/shop/basket/index.svelte',
              name: 'index',
              ext: 'svelte',
              badExt: false,
              absolutePath:
                '/home/jaskaran/repos/enki-website/src/pages/shop/basket/index.svelte',
              importPath: '../src/pages/shop/basket/index.svelte',
              isLayout: false,
              isReset: false,
              isIndex: true,
              isFallback: false,
              isPage: true,
              ownMeta: {},
              meta: {
                recursive: true,
                preload: false,
                prerender: true,
              },
              path: '/shop/basket/index',
              id: '_shop_basket_index',
              component: () =>
                import('../src/pages/shop/basket/index.svelte').then(
                  (m) => m.default
                ),
            },
          ],
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: false,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/basket',
        },
        {
          isFile: true,
          isDir: false,
          file: 'index.svelte',
          filepath: '/shop/index.svelte',
          name: 'index',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/shop/index.svelte',
          importPath: '../src/pages/shop/index.svelte',
          isLayout: false,
          isReset: false,
          isIndex: true,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/index',
          id: '_shop_index',
          component: () =>
            import('../src/pages/shop/index.svelte').then((m) => m.default),
        },
        {
          isFile: false,
          isDir: true,
          file: 'product',
          filepath: '/shop/product',
          name: 'product',
          ext: '',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/shop/product',
          children: [
            {
              isFile: true,
              isDir: false,
              file: '[product].svelte',
              filepath: '/shop/product/[product].svelte',
              name: '[product]',
              ext: 'svelte',
              badExt: false,
              absolutePath:
                '/home/jaskaran/repos/enki-website/src/pages/shop/product/[product].svelte',
              importPath: '../src/pages/shop/product/[product].svelte',
              isLayout: false,
              isReset: false,
              isIndex: false,
              isFallback: false,
              isPage: true,
              ownMeta: {},
              meta: {
                recursive: true,
                preload: false,
                prerender: true,
              },
              path: '/shop/product/:product',
              id: '_shop_product__product',
              component: () =>
                import('../src/pages/shop/product/[product].svelte').then(
                  (m) => m.default
                ),
            },
          ],
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: false,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/product',
        },
        {
          isFile: false,
          isDir: true,
          file: 'search',
          filepath: '/shop/search',
          name: 'search',
          ext: '',
          badExt: false,
          absolutePath:
            '/home/jaskaran/repos/enki-website/src/pages/shop/search',
          children: [
            {
              isFile: true,
              isDir: false,
              file: 'index.svelte',
              filepath: '/shop/search/index.svelte',
              name: 'index',
              ext: 'svelte',
              badExt: false,
              absolutePath:
                '/home/jaskaran/repos/enki-website/src/pages/shop/search/index.svelte',
              importPath: '../src/pages/shop/search/index.svelte',
              isLayout: false,
              isReset: false,
              isIndex: true,
              isFallback: false,
              isPage: true,
              ownMeta: {},
              meta: {
                recursive: true,
                preload: false,
                prerender: true,
              },
              path: '/shop/search/index',
              id: '_shop_search_index',
              component: () =>
                import('../src/pages/shop/search/index.svelte').then(
                  (m) => m.default
                ),
            },
          ],
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: false,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/search',
        },
        {
          isFile: false,
          isDir: true,
          file: 'tag',
          filepath: '/shop/tag',
          name: 'tag',
          ext: '',
          badExt: false,
          absolutePath: '/home/jaskaran/repos/enki-website/src/pages/shop/tag',
          children: [
            {
              isFile: true,
              isDir: false,
              file: '[tag].svelte',
              filepath: '/shop/tag/[tag].svelte',
              name: '[tag]',
              ext: 'svelte',
              badExt: false,
              absolutePath:
                '/home/jaskaran/repos/enki-website/src/pages/shop/tag/[tag].svelte',
              importPath: '../src/pages/shop/tag/[tag].svelte',
              isLayout: false,
              isReset: false,
              isIndex: false,
              isFallback: false,
              isPage: true,
              ownMeta: {},
              meta: {
                recursive: true,
                preload: false,
                prerender: true,
              },
              path: '/shop/tag/:tag',
              id: '_shop_tag__tag',
              component: () =>
                import('../src/pages/shop/tag/[tag].svelte').then(
                  (m) => m.default
                ),
            },
          ],
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: false,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/shop/tag',
        },
      ],
      isLayout: true,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      importPath: '../src/pages/shop/_layout.svelte',
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/shop',
      id: '_shop__layout',
      component: () =>
        import('../src/pages/shop/_layout.svelte').then((m) => m.default),
    },
  ],
  isLayout: true,
  isReset: false,
  isIndex: false,
  isFallback: false,
  isPage: false,
  isFile: true,
  file: '_layout.svelte',
  ext: 'svelte',
  badExt: false,
  importPath: '../src/pages/_layout.svelte',
  meta: {
    recursive: true,
    preload: false,
    prerender: true,
  },
  path: '/',
  id: '__layout',
  component: () => import('../src/pages/_layout.svelte').then((m) => m.default),
};

export const { tree, routes } = buildClientTree(_tree);
