/**
 * @roxi/routify 2.7.3
 * File generated Sat Dec 19 2020 10:08:56 GMT+0000 (Greenwich Mean Time)
 */

export const __version = '2.7.3';
export const __timestamp = '2020-12-19T10:08:56.506Z';

//buildRoutes
import { buildClientTree } from '@roxi/routify/runtime/buildRoutes';

//imports

//options
export const options = {};

//tree
export const _tree = {
  name: '_layout',
  filepath: '/_layout.svelte',
  root: true,
  ownMeta: {},
  absolutePath: '/home/jaskaran/fun/enki-website/src/pages/_layout.svelte',
  children: [
    {
      isFile: true,
      isDir: false,
      file: 'cancel.svelte',
      filepath: '/cancel.svelte',
      name: 'cancel',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/cancel.svelte',
      importPath: '../src/pages/cancel.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/cancel',
      id: '_cancel',
      component: () =>
        import('../src/pages/cancel.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'checkout.svelte',
      filepath: '/checkout.svelte',
      name: 'checkout',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/checkout.svelte',
      importPath: '../src/pages/checkout.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/checkout',
      id: '_checkout',
      component: () =>
        import('../src/pages/checkout.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'classes.svelte',
      filepath: '/classes.svelte',
      name: 'classes',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/classes.svelte',
      importPath: '../src/pages/classes.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/classes',
      id: '_classes',
      component: () =>
        import('../src/pages/classes.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'contact.svelte',
      filepath: '/contact.svelte',
      name: 'contact',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/contact.svelte',
      importPath: '../src/pages/contact.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/contact',
      id: '_contact',
      component: () =>
        import('../src/pages/contact.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'enki.svelte',
      filepath: '/enki.svelte',
      name: 'enki',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/enki.svelte',
      importPath: '../src/pages/enki.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/enki',
      id: '_enki',
      component: () =>
        import('../src/pages/enki.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'index.svelte',
      filepath: '/index.svelte',
      name: 'index',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/index.svelte',
      importPath: '../src/pages/index.svelte',
      isLayout: false,
      isReset: false,
      isIndex: true,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/index',
      id: '_index',
      component: () =>
        import('../src/pages/index.svelte').then((m) => m.default),
    },
    {
      isFile: false,
      isDir: true,
      file: 'online-shop',
      filepath: '/online-shop',
      name: 'online-shop',
      ext: '',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/online-shop',
      children: [
        {
          isFile: true,
          isDir: false,
          file: '[category].svelte',
          filepath: '/online-shop/[category].svelte',
          name: '[category]',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/fun/enki-website/src/pages/online-shop/[category].svelte',
          importPath: '../src/pages/online-shop/[category].svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/online-shop/:category',
          id: '_onlineShop__category',
          component: () =>
            import('../src/pages/online-shop/[category].svelte').then(
              (m) => m.default
            ),
        },
        {
          isFile: true,
          isDir: false,
          file: 'childrens-gifts.svelte',
          filepath: '/online-shop/childrens-gifts.svelte',
          name: 'childrens-gifts',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/fun/enki-website/src/pages/online-shop/childrens-gifts.svelte',
          importPath: '../src/pages/online-shop/childrens-gifts.svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/online-shop/childrens-gifts',
          id: '_onlineShop_childrensGifts',
          component: () =>
            import('../src/pages/online-shop/childrens-gifts.svelte').then(
              (m) => m.default
            ),
        },
        {
          isFile: true,
          isDir: false,
          file: 'gifts.svelte',
          filepath: '/online-shop/gifts.svelte',
          name: 'gifts',
          ext: 'svelte',
          badExt: false,
          absolutePath:
            '/home/jaskaran/fun/enki-website/src/pages/online-shop/gifts.svelte',
          importPath: '../src/pages/online-shop/gifts.svelte',
          isLayout: false,
          isReset: false,
          isIndex: false,
          isFallback: false,
          isPage: true,
          ownMeta: {},
          meta: {
            recursive: true,
            preload: false,
            prerender: true,
          },
          path: '/online-shop/gifts',
          id: '_onlineShop_gifts',
          component: () =>
            import('../src/pages/online-shop/gifts.svelte').then(
              (m) => m.default
            ),
        },
      ],
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: false,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/online-shop',
    },
    {
      isFile: true,
      isDir: false,
      file: 'online-shop.svelte',
      filepath: '/online-shop.svelte',
      name: 'online-shop',
      ext: 'svelte',
      badExt: false,
      absolutePath:
        '/home/jaskaran/fun/enki-website/src/pages/online-shop.svelte',
      importPath: '../src/pages/online-shop.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/online-shop',
      id: '_onlineShop',
      component: () =>
        import('../src/pages/online-shop.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'services.svelte',
      filepath: '/services.svelte',
      name: 'services',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/services.svelte',
      importPath: '../src/pages/services.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/services',
      id: '_services',
      component: () =>
        import('../src/pages/services.svelte').then((m) => m.default),
    },
    {
      isFile: true,
      isDir: false,
      file: 'success.svelte',
      filepath: '/success.svelte',
      name: 'success',
      ext: 'svelte',
      badExt: false,
      absolutePath: '/home/jaskaran/fun/enki-website/src/pages/success.svelte',
      importPath: '../src/pages/success.svelte',
      isLayout: false,
      isReset: false,
      isIndex: false,
      isFallback: false,
      isPage: true,
      ownMeta: {},
      meta: {
        recursive: true,
        preload: false,
        prerender: true,
      },
      path: '/success',
      id: '_success',
      component: () =>
        import('../src/pages/success.svelte').then((m) => m.default),
    },
  ],
  isLayout: true,
  isReset: false,
  isIndex: false,
  isFallback: false,
  isPage: false,
  isFile: true,
  file: '_layout.svelte',
  ext: 'svelte',
  badExt: false,
  importPath: '../src/pages/_layout.svelte',
  meta: {
    recursive: true,
    preload: false,
    prerender: true,
  },
  path: '/',
  id: '__layout',
  component: () => import('../src/pages/_layout.svelte').then((m) => m.default),
};

export const { tree, routes } = buildClientTree(_tree);
