sudo: required
dist: bionic
addons:
  apt:
    packages:
    # These are required to run webkit
    - libwoff1
    - libopus0
    - libwebp6
    - libwebpdemux2
    - libenchant1c2a
    - libgudev-1.0-0
    - libsecret-1-0
    - libhyphen0
    - libgdk-pixbuf2.0-0
    - libegl1
    - libgles2
    - libevent-2.1-6
    - libnotify4
    - libxslt1.1
    - libvpx5
    # gstreamer and plugins to support video playback in WebKit.
    - gstreamer1.0-gl
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    # This is required to run chromium
    - libgbm1
    # this is needed for running headed tests
    - xvfb

# allow headed tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"

node_js:
  - 14

services:
  - docker
  - xvfb

jobs:
  include:
    - stage: "Tests, Linting and Formating"
      script:
        - npm ci
        - npx playwright install
        - npm run lint
        - npm run test:integration
    - stage: "Build and Push Docker Image"
      script:
        - npm ci
        - npm run build
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t jaskaransarkaria/enki-website:"$TRAVIS_TAG" .
        - docker push jaskaransarkaria/enki-website:"$TRAVIS_TAG"
    - stage: Deploy to Kubernetes
      before_install:
        - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      script:
        - kubectl version --client
        - gcloud auth activate-service-account travis-ci-deploy@jobspeed.iam.gserviceaccount.com --key-file=client-secret.json
        - gcloud container clusters get-credentials jobspeed-production --zone europe-west2-a --project jobspeed
        - sed -i "s/replace_with_git_tag/$TRAVIS_TAG/" .kubernetes/deployment.yaml
        - kubectl apply -f .kubernetes/deployment.yaml

stages:
  - name: Tests, Linting and Formating
  - name: Build and Push Docker Image
    if: tag IS present
  - name: Deploy to Kubernetes
    if: tag IS present
