import "@testing-library/jest-dom";
import { vi } from "vitest";
import { tick } from "svelte";
import { render, screen } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import TagView from "./TagView.svelte";
import { refreshTags } from "$lib/utils/requests";

import type { Category } from "$lib/types/category";

vi.mock("$lib/utils/requests");

const mockData: Category[] = [
  {
    Id: 123,
    Name: "Elephant",
    ParentId: null,
    Children: [],
    NominalCode: "",
  },
];

describe("Given TagView", () => {
  beforeEach(() => {
    (refreshTags as jest.Mock).mockResolvedValue([]);
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  describe("WHEN rendered without props and no tags", () => {
    it("THEN show no categories at all", () => {
      const { container } = render(TagView);
      expect(container.children).toHaveLength(1);
    });
  });

  describe("WHEN rendered with props", () => {
    const mockFn = jest.fn();
    it("AND there is no tags data THEN show just the other categories", () => {
      render(TagView, {
        data: mockData,
        categoryFn: mockFn,
      });

      expect(screen.getByTestId("hex-category-name")).toHaveTextContent(
        "Elephant"
      );
      expect(screen.getAllByTestId("hex-category-name")).toHaveLength(1);
    });

    it("AND there is tag data THEN show both tag and other categories", async () => {
      (refreshTags as jest.Mock).mockResolvedValueOnce([
        {
          Id: 789,
          Name: "prefix-Zebra",
          TagTypeId: "999",
        },
      ]);

      const mockFn = jest.fn();

      render(TagView, {
        data: mockData,
        categoryFn: mockFn,
        prefix: "prefix",
      });

      await tick();
      await tick();
      await tick();

      const allDisplayedCats = screen.queryAllByTestId("hex-category-name");
      expect(allDisplayedCats).toHaveLength(2);
      expect(allDisplayedCats[0]).toHaveTextContent("Elephant");
      expect(allDisplayedCats[1]).toHaveTextContent("Zebra");
    });

    it("AND there is multiple tags THEN order the tags alphabetically z to a", async () => {
      (refreshTags as jest.Mock).mockResolvedValueOnce([
        {
          Id: 999,
          Name: "prefix-Ant",
          TagTypeId: "999",
        },
        {
          Id: 789,
          Name: "prefix-Zebra",
          TagTypeId: "999",
        },
      ]);

      const mockFn = jest.fn();

      render(TagView, {
        data: [],
        categoryFn: mockFn,
        prefix: "prefix",
      });

      await tick();
      await tick();
      await tick();

      const allDisplayedCats = screen.queryAllByTestId("hex-category-name");
      expect(allDisplayedCats).toHaveLength(2);
      expect(allDisplayedCats[0]).toHaveTextContent("Zebra");
      expect(allDisplayedCats[1]).toHaveTextContent("Ant");
    });

    it("THEN a non tag category has the href generated by categoryFn", async () => {
      (refreshTags as jest.Mock).mockResolvedValueOnce([
        {
          Id: 789,
          Name: "prefix-Buffalo",
          TagTypeId: "999",
        },
      ]);

      render(TagView, {
        data: mockData,
        categoryFn: () => "mock-href",
        prefix: "prefix",
      });

      await tick();
      await tick();
      await tick();

      const allDisplayedCats = screen.queryAllByTestId("hex-category-name");

      expect(allDisplayedCats).toHaveLength(2);
      expect(allDisplayedCats[0]).toHaveTextContent("Elephant");
      expect(allDisplayedCats[1]).toHaveTextContent("Buffalo");

      const allButtons = screen.queryAllByTestId("hex-link");

      expect(allButtons[0]).toHaveAttribute("href", "mock-href");
    });

    it("THEN a tag category has the href constructed from category id and tag id", async () => {
      (refreshTags as jest.Mock).mockResolvedValueOnce([
        {
          Id: 789,
          Name: "prefix-Buffalo",
          TagTypeId: "999",
        },
      ]);

      render(TagView, {
        data: mockData,
        categoryFn: () => "mock-href",
        prefix: "prefix",
      });

      await tick();
      await tick();
      await tick();

      const allDisplayedCats = screen.queryAllByTestId("hex-category-name");

      expect(allDisplayedCats).toHaveLength(2);
      expect(allDisplayedCats[0]).toHaveTextContent("Elephant");
      expect(allDisplayedCats[1]).toHaveTextContent("Buffalo");

      const allButtons = screen.queryAllByTestId("hex-link");

      expect(allButtons[1]).toHaveAttribute(
        "href",
        `/shop/tag/prefix-buffalo?catid=0&tagid=789`
      );
    });
  });
});
