apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enki
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Cache-Control: public, max-age=7889400";
spec:
  tls:
   - secretName: enki-website-production
     hosts:
       - enkionline.com
       - www.enkionline.com
       - e2e-test.enkionline.com
  rules:
    - host: enkionline.com
      http:
        paths:
          - path: /*
            pathType: "Prefix"
            backend:
              service:
                name: enki-website
                port:
                  number: 5000
    - host: www.enkionline.com
      http:
        paths:
          - path: /*
            pathType: "Prefix"
            backend:
              service:
                name: enki-website
                port:
                  number: 5000
    - host: e2e-test.enkionline.com
      http:
        paths:
          - path: /*
            pathType: "Prefix"
            backend:
              service:
                name: enki-e2e-test-website
                port:
                  number: 5000
