name: Build and Update Image Tag
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build and Push
        run: |
          npm run build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ vars.DOCKER_USERNAME }} --password-stdin
          docker build -t jaskaransarkaria/enki-website:${{ github.ref_name }} .
          docker push jaskaransarkaria/enki-website:${{ github.ref_name }}
        env:
          PUBLIC_SERVER_URL: https://server.enkionline.com
          PUBLIC_STRIPE_KEY: pk_live_51HpvnTAk37gvJ51oKXsYuAZsyletQkgqOky7L2yV9c9nDMj1koLPMvsC6sKBOCqveZMk8CHy730HDFSkiFsbzSRB0059ZpWGau
      - name: Upadate Image Tag
        run: |
          sed -ie "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.ref_name }}/" .kubernetes/deployment.yaml
          sed -ie "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.ref_name }}/" .kubernetes/e2e-test-deployment.yaml
          git add .kubernetes/deployment.yaml
          git add .kubernetes/e2e-test-deployment.yaml
          git commit -m "deploying: bumping image version for release ${{ github.ref_name }}"
          git push https://${{ env.GITHUB_ACCESS_TOKEN }}@github.com/jaskaransarkaria/enki-website.git
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
